// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_about from "./routes/_about.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_game_development from "./routes/_game_development.tsx";
import * as $_games from "./routes/_games.tsx";
import * as $_how_to_stream from "./routes/_how_to_stream.tsx";
import * as $index from "./routes/index.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_about.tsx": $_about,
    "./routes/_app.tsx": $_app,
    "./routes/_game_development.tsx": $_game_development,
    "./routes/_games.tsx": $_games,
    "./routes/_how_to_stream.tsx": $_how_to_stream,
    "./routes/index.tsx": $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
